services:
  crudl:
    container_name: crudl
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: subscriptions
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres 
      PGDATA: /var/lib/postgresql/data/pgdata/
    build: 
      context: .
      dockerfile: dockerfile-crudl
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: subscriptions
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pgdata/
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d subscriptions"]
      interval: 5s
      timeout: 5s
      retries: 10
   

volumes:
  postgres_data:


